### ISSUE TITLE
It always gives an error

### ISSUE THREAD

**Issue by garawaa** [rennanpossas/flutter-easy-project#5]
Command 'EasyProject Flutter: Project set Up' resulted in an error (command 'flutter-easy-project.setupProject' not found)
My vs.code version 1.57.1 flutter plugin version 3.23.0 flutter sdk version 2.2.2

**Comment by rennanpossas** [comment]
Hello @garawaa, sorry for the delay, I was working in another project. I solved this issue in the version 1.1.0. I hope that you can use it now.

Thank you for the report.
